# Generated by Django 6.0.2 on 2026-02-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('cardio', 'Cardiologist'), ('pulmo', 'Pulmonologist'), ('nephro', 'Nephrologist'), ('hepato', 'Hepatologist'), ('endo', 'Endocrinologist')], max_length=20, null=True),
        ),
    ]
