# Generated by Django 6.0.2 on 2026-03-08 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('diabetes_risk', models.FloatField(blank=True, null=True)),
                ('kidney_risk', models.FloatField(blank=True, null=True)),
                ('liver_risk', models.FloatField(blank=True, null=True)),
                ('heart_risk', models.FloatField(blank=True, null=True)),
                ('lung_risk', models.FloatField(blank=True, null=True)),
                ('diabetes_coverage', models.FloatField(blank=True, null=True)),
                ('kidney_coverage', models.FloatField(blank=True, null=True)),
                ('liver_coverage', models.FloatField(blank=True, null=True)),
                ('heart_coverage', models.FloatField(blank=True, null=True)),
                ('lung_coverage', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
